name: 'Checkstyle'
description: 'run checkstyle'
inputs:
  checkstyle_rule:
    description: 'rule'
    default: '/checkstyle_rule.xml'
  checkstyle_result:
    description: 'result'
    default: './checkstyle_result.xml'
runs:
  using: 'docker'
  image: 'Dockerfile'
