name: 'Checkstyle'
description: 'run checkstyle'
inputs:
  rule:
    description: 'rule'
    default: '/checkstyle_rule.xml'
  result:
    description: 'result'
    default: './checkstyle_result.xml'
  workdir:
    description: 'working directory'
    default: '.'
runs:
  using: 'docker'
  image: 'Dockerfile'
