name: Test
on:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run
        uses: iwata-n/actions-checkstyle@main
        with:
          result: result.xml
          rule: .github/workflows/test_rule.xml
          workdir: '.'
      - name: Archive
        uses: actions/upload-artifact@v2
        with:
          name: result
          path: result.xml
